<!--
//+---------------------------------------------------------------------------------------------------------------------------------+
//                                                                                                                                  /
// Copyright (c) 2012 Yahoo! Inc. All rights reserved.                                                                              /
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this                                             /
// file except in compliance with the License. You may obtain a copy of the License at                                              /
//                                                                                                                                  /
//              http://www.apache.org/licenses/LICENSE-2.0                                                                          /
//                                                                                                                                  /
// Unless required by applicable law or agreed to in writing, software distributed under                                            /
// the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF                                              /
// ANY KIND, either express or implied. See the License for the specific language governing                                         /
// permissions and limitations under the License. See accompanying LICENSE file.                                                    /
//                                                                                                                                  /
// $Author:shawcs@yahoo-inc.com  $Date: 30-Jan-2012                                                                                 /
//                                                                                                                                  /
//+---------------------------------------------------------------------------------------------------------------------------------+
-->
<style type="text/css">
<!--
tr.hide        { visibility: hidden; display: none; }
tr.show        { visibility: visible; display: table-row; }
-->
</style>
<div style="background-color:#9BF8FB">
<table cellspacing=1 cellpadding=1 border=0 width=100%>
<tr><td width=100%>
<table cellspacing=1 cellpadding=1 border=0 width=100%>
<?php 
$by_url = __EMPLOYEE_PROFILE;
if($this->showTime == 1 && $this->is_allowed && $this->hideothers!=1) {
?>
<tr><td colspan=2><table cellspacing=0 cellpadding=0 border=0 width=962>
<tr>
<td align=right><table cellspacing=2 cellpadding=2 border=0><tr>
<?php
  foreach($this->timezones as $timezone) {
?>
<td><a onClick="return checkBCP()" href="javascript:showDialog('edit_time','./calendar.php?action=<?=$this->timeaction?>&aid=<?=$timezone[assigneetime_id]?>','215','330','OnCall Time')"><img src='./images/clock_edit.png' border=0></a>&nbsp;<a onClick="return checkBCP()" href="javascript:showDialog('edit_time','./calendar.php?action=<?=$this->timeaction?>&aid=<?=$timezone[assigneetime_id]?>','215','330','OnCall Time')"><?=$timezone[timezone]?>&nbsp;Session &nbsp;[<?=$timezone[start_time]?>-<?=$timezone[end_time]?>&nbsp;PST]</a>
<?php
    if($this->storageCall == 1) {
?>
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Escalation Manager : <a target=_blank href=<?=$by_url.$timezone[escalation_manager]?> href><?=$timezone[escalation_manager]?></a>]</br>
<?php
    }
?>
</td>
<?php
  }
?>
</tr>
</table>
</td>
</tr></table></td></tr>
<?php
}
else {
?>
<tr><td colspan=2><table cellspacing=0 cellpadding=0 border=0 width=962>
<tr><td>&nbsp;</td>
<td align=right><table cellspacing=2 cellpadding=2 border=0><tr>
<?php
  foreach($this->timezones as $timezone) {
?>
<td><img src='./images/clock_edit.png' border=0>&nbsp; <?=$timezone[timezone]?>&nbsp;Oncall&nbsp;[<?=$timezone[start_time]?>-<?=$timezone[end_time]?>&nbsp;PST]
<?php
    if($this->storageCall == 1) {
?>
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Escalation Manager : <a target=_blank href=<?=$by_url.$timezone[escalation_manager]?> href><?=$timezone[escalation_manager]?></a>]</br>
<?php
    }
?>
</td>
<?php
  }
?>
</tr>
</table>
</td>
</tr></table></td></tr>
<?php
}
?>

</tr>
</table>
</td>
</tr></table>

<tr><td width=962>

<form name='callist' method='post' action="./calendar.php?action=<?=$this->action?>">
<select name ="teamname" onChange="document.forms['callist'].submit()">
<?php
   $teams = $this->teamlist;
   if(!$_POST['teamname'])
	   $team = "Select a Team";
   else
           $team = $_POST['teamname'];
  ?>
    <option selected> <?=$team  ?></option>
  <?php
  for($i =0; $i <count($teams); $i +=1)
  {
   if($teams[$i]['team_name']!=$team)
   {
   	?>
   	 <option> <?= $teams[$i]['team_name'] ?></option>
<?php
   }
  }
	?>
</select>
<br/>
<br/>
<center>
<input type=hidden name=year id=year>
<input type=hidden name=month id=month>
<table border=0 cellspacing=0 cellpadding=0 width=962 height=700 background='#000000'>
<tr><td width=100% valign=top>
<table border=0 cellspacing=0 cellpadding=0 width=100%>
<tr><center><font size = 4 color=#9900CC ><b><u><?php if($team != "Select a Team") echo $team." Calendar" ?></u></b></font></center></tr>
<tr><td width=50% align=left>

<?php
if($this->hideothers!=1) {
?>
<table><tr><td><a href="javascript:showDetails('<?=$this->cal->prev_year?>','<?=$this->cal->prev_month?>')"><img src='./images/arrow_left.png' alt='Previous Month' border=0></a></td><td>&nbsp;&nbsp;</td>
</tr></table>
<?php
}
?>
</td>
<td>

<td width=50% align=right><table><tr><td>
<?php
if($this->is_allowed && $this->hideothers!=1){
?>
<table><tr><td width=10><a onClick="return checkBCP()" href="./calendar.php?action=<?=$this->next_action?>"><img src='./images/calendar_edit.png' border=0 alt='add'></a></td><td><ul class="button"><li class="button"><a onClick="return checkBCP()" href="./calendar.php?action=<?=$this->next_action?>&team=<?=$this->team?>" class="button">Add/Edit Schedule</a></li></ul></td></tr></table>
<?php
}
?>
</td><td>&nbsp;&nbsp;</td><td>
<?php
if($this->hideothers!=1) {
?>
<a href="javascript:showDetails('<?=$this->cal->next_year?>','<?=$this->cal->next_month?>')"><img src='./images/arrow_right.png' alt='Next Month' border=0></a>
<?php
}
?>
</td></tr>
</table></td></tr></table> 
</td></tr>
<tr class='calbg'><td valign=top width=100% height=100%>
<table border=0 cellspacing=1 cellpadding=1 width=100% height=100%>
<thead>
<tr height=20><th align=center colspan=7><?=$this->cal->caption?></th></tr>
<tr height=20>
<?php
$int_cnt = 0;
foreach($this->cal->wdays as $day)
{
?>
<th align=center><?=$day?></th>
<?php 
}
?>
</tr>
</thead>
<tbody>
	<tr bgcolor="#F7F7F7">
	<?php

	if($this->cal->startday>0) {
	for($blnk=1;$blnk<=$this->cal->startday;$blnk++) {
	$int_cnt++;
	?>
	<td>&nbsp;</td>
	<?	
	}
	}
	for($day=1;$day<=$this->cal->days;$day++) {
		$int_cnt++;
		$class= '';
		if ($this->cal->highlight && $day == $this->cal->curr_day) {
			$class = " class='lighttd'";
		} else {
}
		$ts = strtotime($this->cal->month_year."-".$day);
		$str_tbl = "<table width=100% width=100% cellspacing=0 cellpadding=0><tr><td valign=top align=right><font class='title'>$day</font></td></tr><tr><td>&nbsp;</td></tr><tr><td align=right><table border=0 cellspacing=0 cellpadding=0>";
		
		foreach($this->assignee as $rec) {
			if(strtotime($rec[from_dt])<=$ts && strtotime($rec[to_dt])>=$ts) {
			if($this->onCall == 1) {
			$href = $rec[oncall_type]==1?" class='href_green'":" class='href_blue'";
			$details = "<a target=_blank href='".$by_url.$rec[username]."' $href>$rec[username]</a>".",".$rec[timezone].($rec[oncall_type]==1?"(P)":"(S)");
			$t_class = $rec[oncall_type]==1?" class='text_green'":" class='text_blue'";
			} else if($this->vacationCal == 1) {
				$t_class=" class='text_green'";
				$details = "<a target=_blank href='".$by_url.$rec[username]."' class='href_green'>$rec[username]</a>".",".$rec[vctype].(trim($rec[vc_comment])!=''?("(".$rec[vc_comment].")"):'');
			} else if($this->CMRCal == 1) {
				$t_class=" class='text_green'";
                                $details = "<a target=_blank href='".$by_url.$rec[username]."' class='href_green'>$rec[username]</a>"."(".$rec[timezone].")";
			}  else if($this->tapeops == 1) {
				$t_class=" class='text_green'";
                                $details = "<a target=_blank href='".$by_url.$rec[username]."' class='href_green'>$rec[username]</a>"."(".$rec[region].")";
			} else if($this->infravacationCal == 1) {
				$t_class=" class='text_green'";
				$details = "<a target=_blank href='".$by_url.$rec[username]."' class='href_green'>$rec[username]</a>".",".$rec[vctype].(trim($rec[vc_comment])!=''?("(".$rec[vc_comment].")"):'');
			} 
			else {
			}
			$str_tbl.="<tr><td align=right><font $t_class> $details</font></td></tr>";
			}
		}
		$str_tbl.="</table>";
		$str_tbl.="</td></tr></table>";
		
		?>
		<td valign=top align=right height=100 width=100 <?=$class?>><?=$str_tbl?></td>
		<?php
			if($int_cnt%7==0 && $this->cal->days==$day) {
		?>
				</tr>
		<?
			} else if($int_cnt%7==0) {
		?>
				</tr><tr bgcolor="#F7F7F7">
		<?php
			} else { } ?>
	<?php
	}

		$rem = $int_cnt%7;
		if($rem>0) {
		$rcols = 7-$rem;
		for($int_r=1;$int_r<=$rcols;$int_r++) {
		?>
		<td>&nbsp;</td>
		<?php
		}
		?>
		</tr>
		<?php
		}
		?>
</tbody>
</table>
</td></tr>
</table>
</form>
</td><td valign=top align=left>
<br><br>


</td></tr>
</table>
</td></tr></table>

<script langauge='javascript'>
function showDetails(yr,mon) {
        document.getElementById('year').value = yr;
        document.getElementById('month').value = mon;
        document.callist.submit();
}
</script>
