<?
//+---------------------------------------------------------------------------------------------------------------------------------+
//                                                                                                                                  /
// Copyright (c) 2012 Yahoo! Inc. All rights reserved.                                                                              /
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this                                             /
// file except in compliance with the License. You may obtain a copy of the License at                                              /
//                                                                                                                                  /
//              http://www.apache.org/licenses/LICENSE-2.0                                                                          /
//                                                                                                                                  /
// Unless required by applicable law or agreed to in writing, software distributed under                                            /
// the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF                                              /
// ANY KIND, either express or implied. See the License for the specific language governing                                         /
// permissions and limitations under the License. See accompanying LICENSE file.                                                    /
//                                                                                                                                  /
// $Author:shawcs@yahoo-inc.com  $Date: 30-Jan-2012                                                                                 /
//                                                                                                                                  /
//+---------------------------------------------------------------------------------------------------------------------------------+

  $messages = OpsContext::get('messages');
  $errors = $messages->errors;
  $flashes = $messages->flashes;
  $width=($this->hideheader!=1)?"40%":"100%";
?>
<? if($errors): ?>
<table width="<?php echo $width?>" border=0 cellspacing=2 cellpadding=2>
<tr><td>
<div class="error">
  <ul>
  <? foreach($errors as $error): ?>
    <li><?php echo  $error ?></li>
  <? endforeach ?>
  </ul>
</div>
</td></tr></table>
<? endif ?>

<? if($flashes): ?>
<div class="notice">
  <ul>
  <? foreach($flashes as $flash): ?>
    <li><?php echo  $flash ?></li>
  <? endforeach ?>
  </ul>
</div>
<? endif ?>
